#! /bin/bash

if [ -f /Volumes/rdisk/ramdisk-id ]; then
    TDIR=$(mktemp -d /Volumes/rdisk/ad-test.XXXXXX)
else
    TDIR=$(mktemp -d)
fi
# echo "TDIR $TDIR"
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

export LD_LIBRARY_PATH="$HOME"/AD/lib
cd "$TESTDIR"

OUPUT="$TDIR/2004nd-003.$(date +%Y%m%d-%H%M).pdf"
../bin/acmacs-map-draw -m -s 2004nd-003.json 2004nd-003.ace "$OUPUT"
if [[ "$(uname)" == "Darwin" && "$1" == "-v" ]]; then
    open "$OUPUT" && sleep 3
fi

# ======================================================================
# Local Variables:
# eval: (if (fboundp 'eu-rename-buffer) (eu-rename-buffer))
# End:
