#! /bin/bash

TDIR=$(mktemp -d)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

export LD_LIBRARY_PATH="$HOME"/AD/lib
cd "$TESTDIR"

../bin/acmacs-map-draw -m -s 2004nd-003.json 2004nd-003.ace "$TDIR/2004nd-003.pdf"
# open "$TDIR/2004nd-003.pdf" && sleep 3

# ======================================================================
# Local Variables:
# eval: (if (fboundp 'eu-rename-buffer) (eu-rename-buffer))
# End:
